In [1]:
import os
import sys

os.chdir("C:/dataanalytics/python")
os.curdir

#Configure the environment . Set this up to the directory where spark is installed
if 'SPARK_HOME' not in os.environ:
    os.environ['SPARK_HOME'] = 'C:\\spark'
    
#create a variable for our root path
SPARK_HOME = os.environ['SPARK_HOME']

#Add the following paths to the system path. Please check your installation
#to make sure that these zip files actually exists. The names might change as
#versions change
sys.path.insert(0,os.path.join(SPARK_HOME,"python"))
sys.path.insert(0,os.path.join(SPARK_HOME,"python","lib"))
sys.path.insert(0,os.path.join(SPARK_HOME,"python","lib","py4j-0.10.4-src.zip"))
sys.path.insert(0,os.path.join(SPARK_HOME,"python","lib","pyspark.zip"))
 
#Initialize a spark context
from pyspark import SparkContext
from pyspark import SparkConf

#optionally configure spark
conf = SparkConf()
conf.setAppName("Jeffwiz")

#Initalize spark context onl runs once
sc = SparkContext('local', conf=conf)



In [2]:
from pyspark.mllib.feature import HashingTF

In [3]:
sentence = "hello hello world"

In [4]:
words = sentence.split() # Split sentence into a list of terms

In [5]:
words

['hello', 'hello', 'world']

In [6]:
tf = HashingTF(10000) # Create vectors of size S = 10,000

In [7]:
tf

In [8]:
tf.transform(words)

SparseVector(10000, {3220: 1.0, 6497: 2.0})

In [9]:
from pyspark.mllib.classification import LogisticRegressionWithSGD

In [10]:
from pyspark.mllib.regression import LabeledPoint

In [11]:
from pyspark.mllib.feature import HashingTF

In [12]:
data = [
     LabeledPoint(0.0, [0.0, 1.0]),
     LabeledPoint(1.0, [1.0, 0.0]),
    ]

In [13]:
lrm = LogisticRegressionWithSGD.train(sc.parallelize(data), iterations=10)

C:\spark\python\lib\pyspark.zip\pyspark\mllib\classification.py:313: UserWarning: Deprecated in 2.0.0. Use ml.classification.LogisticRegression or LogisticRegressionWithLBFGS.


In [14]:
lrm.predict([1.0, 0.0])

1

In [15]:
lrm.predict([0.0, 1.0])

0

In [16]:
lrm.predict(sc.parallelize([[1.0, 0.0], [0.0, 1.0]])).collect()

[1, 0]

In [2]:
from pyspark.mllib.linalg import Vectors

In [3]:
denseVec2 = Vectors.dense([1.0, 2.0, 3.0]) # .. or you can use the Vectors class
print(denseVec2)

[1.0,2.0,3.0]


In [4]:
sparseVec1 = Vectors.sparse(4, {0: 1.0, 2: 2.0})
print(sparseVec1)

(4,[0,2],[1.0,2.0])


In [5]:
# These can be passed as a dictionary or as two lists of indices and values.
sparseVec1 = Vectors.sparse(4, {0: 1.0, 2: 2.0})
sparseVec2 = Vectors.sparse(4, [0, 2], [1.0, 2.0])

In [6]:
from pyspark.mllib.feature import HashingTF, IDF

In [7]:
sentence = "hello hello world"
words = sentence.split() # Split sentence into a list of terms
tf = HashingTF(10000) # Create vectors of size S = 10,000
tf.transform(words)

SparseVector(10000, {3708: 1.0, 5532: 2.0})

In [2]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.regression import LinearRegressionWithSGD
from pyspark.mllib.classification import LogisticRegressionWithLBFGS
from pyspark.mllib.linalg import Vectors
from pyspark.mllib.feature import HashingTF, IDF
from pyspark.mllib.classification import SVMWithSGD
from pyspark.mllib.classification import NaiveBayes
from pyspark.mllib.clustering import KMeans
from pyspark.mllib.clustering import BisectingKMeans
from pyspark.mllib.classification import StreamingLogisticRegressionWithSGD
from pyspark.mllib.clustering import GaussianMixture
from pyspark.mllib.clustering import PowerIterationClustering
from pyspark.mllib.clustering import StreamingKMeans
from pyspark.mllib.clustering import LDA
#one for from pyspark.mllib.evaluation BinaryClassificationMetrics
from pyspark.mllib.feature import Normalizer
from pyspark.mllib.feature import StandardScaler
from pyspark.mllib.feature import Word2Vec
from pyspark.mllib.feature import ChiSqSelector
from pyspark.mllib.feature import ElementwiseProduct
from pyspark.mllib.fpm import PrefixSpan
from pyspark.mllib.linalg import Matrix
from pyspark.mllib.linalg import SparseMatrix
from pyspark.mllib.linalg import QRDecomposition
#for distributed matrixes check version
from pyspark.mllib.random import RandomRDDs
from pyspark.mllib.recommendation import MatrixFactorizationModel
from pyspark.mllib.regression import RidgeRegressionModel
from pyspark.mllib.regression import LassoModel
from pyspark.mllib.regression import IsotonicRegression
from pyspark.mllib.stat import Statistics
from pyspark.mllib.tree import DecisionTree
from pyspark.mllib.tree import RandomForest
from pyspark.mllib.tree import GradientBoostedTrees
from pyspark.mllib.util import JavaLoader
from pyspark.mllib.util import LinearDataGenerator
from pyspark.mllib.util import Loader
from pyspark.mllib.util import MLUtils







In [3]:
data = [
     LabeledPoint(0.0, [0.0, 1.0]),
     LabeledPoint(1.0, [1.0, 0.0]),
      ]

In [6]:
from pyspark.mllib.classification import LogisticRegressionWithSGD

In [7]:
lrm = LogisticRegressionWithSGD.train(sc.parallelize(data), iterations=10)

C:\spark\python\lib\pyspark.zip\pyspark\mllib\classification.py:313: UserWarning: Deprecated in 2.0.0. Use ml.classification.LogisticRegression or LogisticRegressionWithLBFGS.


In [8]:
lrm.predict([1.0, 0.0])

1

In [9]:
lrm.predict([0.0, 1.0])

0

In [10]:
lrm.predict(sc.parallelize([[1.0, 0.0], [0.0, 1.0]])).collect()

[1, 0]

In [11]:
 lrm.clearThreshold()

In [12]:
lrm.predict([1.0, 0.0])

0.7207080310200239

In [13]:
data = [
     LabeledPoint(0.0, [0.0, 1.0]),
     LabeledPoint(1.0, [1.0, 0.0]),
      ]
lrm = LogisticRegressionWithSGD.train(sc.parallelize(data), iterations=10)
lrm.predict([0.0,1.0])
lrm.predict([1.0,0.0])
lrm.predict(sc.parallelize([[1.0, 0.0], [0.0, 1.0]])).collect()

C:\spark\python\lib\pyspark.zip\pyspark\mllib\classification.py:313: UserWarning: Deprecated in 2.0.0. Use ml.classification.LogisticRegression or LogisticRegressionWithLBFGS.


[1, 0]

In [3]:
sparse_data = [
     LabeledPoint(0.0, Vectors.sparse(2, {0: 0.0})),
     LabeledPoint(1.0, Vectors.sparse(2, {1: 1.0})),
     LabeledPoint(0.0, Vectors.sparse(2, {0: 1.0})),
     LabeledPoint(1.0, Vectors.sparse(2, {1: 2.0}))
              ]
lrm = LogisticRegressionWithLBFGS.train(sc.parallelize(sparse_data), iterations=10)
lrm.predict(array([0.0, 1.0]))
lrm.predict(array([1.0, 0.0]))
lrm.predict(Vectors.sparse(2, {1: 1.0}))
lrm.predict(Vectors.sparse(2, {0: 1.0}))


NameError: name 'array' is not defined

In [16]:
sparse_data = [
     LabeledPoint(0.0, Vectors.sparse(2, {0: 0.0})),
     LabeledPoint(1.0, Vectors.sparse(2, {1: 1.0})),
     LabeledPoint(0.0, Vectors.sparse(2, {0: 1.0})),
     LabeledPoint(1.0, Vectors.sparse(2, {1: 2.0}))
              ]

In [18]:
mrm = LogisticRegressionWithSGD.train(sc.parallelize(sparse_data), iterations=10)

C:\spark\python\lib\pyspark.zip\pyspark\mllib\classification.py:313: UserWarning: Deprecated in 2.0.0. Use ml.classification.LogisticRegression or LogisticRegressionWithLBFGS.
  "Deprecated in 2.0.0. Use ml.classification.LogisticRegression or "


In [20]:
lrm.predict(Vectors.sparse(2, {1: 1.0}))

0

In [21]:
#multiclass data
multi_class_data = [
     LabeledPoint(0.0, [0.0, 1.0, 0.0]),
     LabeledPoint(1.0, [1.0, 0.0, 0.0]),
     LabeledPoint(2.0, [0.0, 0.0, 1.0])
              ]

In [22]:
data = sc.parallelize(multi_class_data)

In [24]:
mcm = LogisticRegressionWithSGD.train(data, iterations=10, numClasses=3)

TypeError: train() got an unexpected keyword argument 'numClasses'

In [3]:
#principal component analysis
from pyspark.mllib.linalg import Vectors
from pyspark.mllib.linalg.distributed import RowMatrix

In [7]:
# $example on$
rows = sc.parallelize([
        Vectors.sparse(5, {1: 1.0, 3: 7.0}),
        Vectors.dense(2.0, 0.0, 3.0, 4.0, 5.0),
        Vectors.dense(4.0, 0.0, 0.0, 6.0, 7.0)
    ])

mat = RowMatrix(rows)

# Compute the top 5 singular values and corresponding singular vectors.
svd = mat.computeSVD(5, computeU=True)
U = svd.U       # The U factor is a RowMatrix.
s = svd.s       # The singular values are stored in a local dense vector.
V = svd.V       # The V factor is a local dense matrix.
# $example off$
collected = U.rows.collect()
print("U factor is:")
for vector in collected:
        print(vector)
        print("Singular values are: %s" % s)
        print("V factor is:\n%s" % V)

U factor is:
[-0.38829130511665644,-0.9198099362554474,-0.056387441301709175,9.313225746154785e-09,0.0]
Singular values are: [13.029275535600473,5.368578733451684,2.5330498218813755,6.323166049206486e-08,2.0226934557075942e-08]
V factor is:
DenseMatrix([[-0.31278534,  0.31167136,  0.30366911,  0.8409913 , -0.07446478],
             [-0.02980145, -0.17133211, -0.02226069,  0.14664984,  0.97352733],
             [-0.12207248,  0.15256471, -0.95070998,  0.23828799, -0.03452092],
             [-0.71847899, -0.68096285, -0.0172245 , -0.02094998, -0.13907533],
             [-0.60841059,  0.62170723,  0.05606596, -0.46260933,  0.16175873]])
[-0.5301719995198351,0.2730185511901228,-0.8027319114319463,0.0,0.0]
Singular values are: [13.029275535600473,5.368578733451684,2.5330498218813755,6.323166049206486e-08,2.0226934557075942e-08]
V factor is:
DenseMatrix([[-0.31278534,  0.31167136,  0.30366911,  0.8409913 , -0.07446478],
             [-0.02980145, -0.17133211, -0.02226069,  0.14664984,  0.973

In [9]:
from pyspark.mllib.linalg import Vectors
from pyspark.mllib.linalg.distributed import RowMatrix

#$example on$
rows = sc.parallelize([
        Vectors.sparse(5, {1: 1.0, 3: 7.0}),
        Vectors.dense(2.0, 0.0, 3.0, 4.0, 5.0),
        Vectors.dense(4.0, 0.0, 0.0, 6.0, 7.0)
    ])

mat = RowMatrix(rows)
# Compute the top 4 principal components.
# Principal components are stored in a local dense matrix.
pc = mat.computePrincipalComponents(4)

# Project the rows to the linear space spanned by the top 4 principal components.
projected = mat.multiply(pc)
# $example off$
collected = projected.rows.collect()
print("Projected Row Matrix of principal component:")
for vector in collected:
        print(vector)

Projected Row Matrix of principal component:
[1.6485728230883807,-4.013282700516296,-5.524543751369388,0.1725834469163086]
[-4.645104331781533,-1.1167972663619026,-5.524543751369387,0.17258344691630922]
[-6.428880535676489,-5.337951427775355,-5.524543751369389,0.17258344691630967]


In [3]:
autoData = sc.textFile(r"C:\Users\jeffnerd\Desktop\spark\auto-miles-per-gallon.csv")

In [4]:
autoData.cache()

C:\Users\jeffnerd\Desktop\spark\auto-miles-per-gallon.csv MapPartitionsRDD[1] at textFile at <unknown>:0

In [5]:
#Remove the first line (contains headers)
dataLines = autoData.filter(lambda x: "CYLINDERS" not in x)
dataLines.count()

398

In [38]:
import math
from pyspark.ml.linalg import DenseVector
from pyspark.mllib.stat import Statistics
from pyspark.sql import SQLContext
from pyspark.ml.regression import LinearRegression

In [39]:
#Use default for average HP
avgHP =sc.broadcast(80.0)

In [40]:
def transformToNumeric( inputStr) :
    global avgHP
    attList=inputStr.split(",")
    
    #Replace ? values with a normal value
    hpValue = attList[3]
    if hpValue == "?":
        hpValue=avgHP.value
       
    #Filter out columns not wanted at this stage
    values= DenseVector([ float(attList[0]), \
                     float(attList[1]),  \
                     hpValue,    \
                     float(attList[5]),  \
                     float(attList[6])
                     ])
    return values

In [41]:
#Keep only MPG, CYLINDERS, HP,ACCELERATION and MODELYEAR
autoVectors = dataLines.map(transformToNumeric)
autoVectors.collect()


[DenseVector([18.0, 8.0, 130.0, 12.0, 70.0]),
 DenseVector([15.0, 8.0, 165.0, 11.5, 70.0]),
 DenseVector([18.0, 8.0, 150.0, 11.0, 70.0]),
 DenseVector([16.0, 8.0, 150.0, 12.0, 70.0]),
 DenseVector([17.0, 8.0, 140.0, 10.5, 70.0]),
 DenseVector([15.0, 8.0, 198.0, 10.0, 70.0]),
 DenseVector([14.0, 8.0, 220.0, 9.0, 70.0]),
 DenseVector([14.0, 8.0, 215.0, 8.5, 70.0]),
 DenseVector([14.0, 8.0, 225.0, 10.0, 70.0]),
 DenseVector([15.0, 8.0, 190.0, 8.5, 70.0]),
 DenseVector([15.0, 8.0, 170.0, 10.0, 70.0]),
 DenseVector([14.0, 8.0, 160.0, 8.0, 70.0]),
 DenseVector([15.0, 8.0, 150.0, 9.5, 70.0]),
 DenseVector([14.0, 8.0, 225.0, 10.0, 70.0]),
 DenseVector([24.0, 4.0, 95.0, 15.0, 70.0]),
 DenseVector([22.0, 6.0, 95.0, 15.5, 70.0]),
 DenseVector([18.0, 6.0, 97.0, 15.5, 70.0]),
 DenseVector([21.0, 6.0, 85.0, 16.0, 70.0]),
 DenseVector([27.0, 4.0, 88.0, 14.5, 70.0]),
 DenseVector([26.0, 4.0, 46.0, 20.5, 70.0]),
 DenseVector([25.0, 4.0, 87.0, 17.5, 70.0]),
 DenseVector([24.0, 4.0, 90.0, 14.5, 70.0]),
 

In [42]:
autoStats=Statistics.colStats(autoVectors)

Py4JJavaError: An error occurred while calling o267.colStats.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 21.0 failed 1 times, most recent failure: Lost task 0.0 in stage 21.0 (TID 21, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\spark\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\spark\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "C:\spark\python\lib\pyspark.zip\pyspark\mllib\linalg\__init__.py", line 83, in _convert_to_vector
    raise TypeError("Cannot convert type %s into Vector" % type(l))
TypeError: Cannot convert type <class 'pyspark.ml.linalg.DenseVector'> into Vector

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2119)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1026)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1008)
	at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1.apply(RDD.scala:1151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.treeAggregate(RDD.scala:1128)
	at org.apache.spark.mllib.linalg.distributed.RowMatrix.computeColumnSummaryStatistics(RowMatrix.scala:419)
	at org.apache.spark.mllib.stat.Statistics$.colStats(Statistics.scala:46)
	at org.apache.spark.mllib.api.python.PythonMLLibAPI.colStats(PythonMLLibAPI.scala:837)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "C:\spark\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "C:\spark\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "C:\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "C:\spark\python\lib\pyspark.zip\pyspark\mllib\linalg\__init__.py", line 83, in _convert_to_vector
    raise TypeError("Cannot convert type %s into Vector" % type(l))
TypeError: Cannot convert type <class 'pyspark.ml.linalg.DenseVector'> into Vector

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more


In [12]:
autoStats.mean()

array([ 23.51457286,   5.45477387, 104.10050251,  15.56809045,
        76.01005025])

In [13]:
autoStats.variance()

array([  61.08961077,    2.89341544, 1468.09062947,    7.60484823,
         13.67244282])

In [14]:
autoStats.min()

array([ 9.,  3., 46.,  8., 70.])

In [15]:
autoStats.max()


array([ 46.6,   8. , 230. ,  24.8,  82. ])

In [16]:
Statistics.corr(autoVectors)

array([[ 1.        , -0.77539629, -0.77463084,  0.42028891,  0.57926713],
       [-0.77539629,  1.        ,  0.84275215, -0.50541949, -0.3487458 ],
       [-0.77463084,  0.84275215,  1.        , -0.68829885, -0.41559383],
       [ 0.42028891, -0.50541949, -0.68829885,  1.        ,  0.28813695],
       [ 0.57926713, -0.3487458 , -0.41559383,  0.28813695,  1.        ]])

In [17]:
sqlContext = SQLContext(sc)


In [18]:
def transformToLabeledPoint(inStr) :
    lp = ( float(inStr[0]), Vectors.dense([inStr[1],inStr[2],inStr[4]]))
    return lp

In [21]:
autoLp = autoVectors.map(transformToLabeledPoint)

In [22]:
autoDF = sqlContext.createDataFrame(autoLp,["label", "features"])
autoDF.select("label","features").show(10)


+-----+----------------+
|label|        features|
+-----+----------------+
| 18.0|[8.0,130.0,70.0]|
| 15.0|[8.0,165.0,70.0]|
| 18.0|[8.0,150.0,70.0]|
| 16.0|[8.0,150.0,70.0]|
| 17.0|[8.0,140.0,70.0]|
| 15.0|[8.0,198.0,70.0]|
| 14.0|[8.0,220.0,70.0]|
| 14.0|[8.0,215.0,70.0]|
| 14.0|[8.0,225.0,70.0]|
| 15.0|[8.0,190.0,70.0]|
+-----+----------------+
only showing top 10 rows



In [24]:
#Split into training and testing data
(trainingData, testData) = autoDF.randomSplit([0.9, 0.1])
trainingData.count()


363

In [25]:
testData.count()

35

In [26]:
lr = LinearRegression(maxIter=10)

In [27]:
lrModel = lr.fit(trainingData)

IllegalArgumentException: 'requirement failed: Column features must be of type org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7 but was actually org.apache.spark.mllib.linalg.VectorUDT@f71b0bce.'

In [ ]:
lrModel = lr.fit(trainingData)

print("Coefficients: " + str(lrModel.coefficients))
print("Intercept: " + str(lrModel.intercept))

#Predict on the test data
predictions = lrModel.transform(testData)
predictions.select("prediction","label","features").show()

from pyspark.ml.evaluation import RegressionEvaluator
evaluator = RegressionEvaluator(predictionCol="prediction", \
                 labelCol="label",metricName="r2")
evaluator.evaluate(predictions)


In [28]:
from pyspark.ml.linalg import DenseVector

In [31]:
y = DenseVector([0,1])

In [33]:
y

DenseVector([0.0, 1.0])

In [43]:
from pyspark.ml.linalg import Vectors
from pyspark.ml.classification import LogisticRegression


In [45]:
# Prepare training data from a list of (label, features) tuples.
training = sqlContext.createDataFrame([
    (1.0, Vectors.dense([0.0, 1.1, 0.1])),
    (0.0, Vectors.dense([2.0, 1.0, -1.0])),
    (0.0, Vectors.dense([2.0, 1.3, 1.0])),
    (1.0, Vectors.dense([0.0, 1.2, -0.5]))], ["label", "features"])

In [47]:
 #Create a LogisticRegression instance. This instance is an Estimator.
lr = LogisticRegression(maxIter=10, regParam=0.01)
# Print out the parameters, documentation, and any default values.
print("LogisticRegression parameters:\n" + lr.explainParams() + "\n")

LogisticRegression parameters:
aggregationDepth: suggested depth for treeAggregate (>= 2). (default: 2)
elasticNetParam: the ElasticNet mixing parameter, in range [0, 1]. For alpha = 0, the penalty is an L2 penalty. For alpha = 1, it is an L1 penalty. (default: 0.0)
family: The name of family which is a description of the label distribution to be used in the model. Supported options: auto, binomial, multinomial (default: auto)
featuresCol: features column name. (default: features)
fitIntercept: whether to fit an intercept term. (default: True)
labelCol: label column name. (default: label)
maxIter: max number of iterations (>= 0). (default: 100, current: 10)
predictionCol: prediction column name. (default: prediction)
probabilityCol: Column name for predicted class conditional probabilities. Note: Not all models output well-calibrated probability estimates! These probabilities should be treated as confidences, not precise probabilities. (default: probability)
rawPredictionCol: raw predi

In [48]:
# Learn a LogisticRegression model. This uses the parameters stored in lr.
model1 = lr.fit(training)

In [49]:
 #Since model1 is a Model (i.e., a transformer produced by an Estimator),
# we can view the parameters it used during fit().
# This prints the parameter (name: value) pairs, where names are unique IDs for this
# LogisticRegression instance.
print("Model 1 was fit using parameters: ")
print(model1.extractParamMap())

Model 1 was fit using parameters: 
{}
