In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[1:7:2]

array([1, 3, 5])

In [5]:
x[-2:10]

array([8, 9])

In [6]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [7]:
x[5:]

array([5, 6, 7, 8, 9])

In [9]:
x = np.array([[[1],[2],[3]],[[4],[5],[6]]])

In [10]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [11]:
x[0]

array([[1],
       [2],
       [3]])

In [12]:
x.shape

(2, 3, 1)

In [13]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [14]:
#ellipsis
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x[:, np.newaxis,:,:]

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]]])

In [17]:
x.shape

(2, 3, 1)

In [18]:
x[:, np.newaxis,:,:].shape

(2, 1, 3, 1)

In [19]:
#advanced indexing
x = np.array([[1,2],[3,4],[5,6]])

In [20]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
x[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [22]:
#another example
x = np.array([[0,1,2],
             [3,4,5],
             [6,7,8],
             [9,10,11]])

In [23]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
x.shape

(4, 3)

In [25]:
rows = np.array([[0,0],
                [3,3]], dtype = np.intp)
columns = np.array([[0,2],
                   [0,2]], dtype = np.intp)


In [26]:
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [27]:
rows = np.array([0,3], dtype=np.intp)
columns = np.array([0,2], dtype=np.intp)

In [28]:
x[rows[:,np.newaxis], columns ]

array([[ 0,  2],
       [ 9, 11]])

In [30]:
columns

array([0, 2], dtype=int64)

In [31]:
#for broadcasting we can use np.ix_
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [2]:
#nditer iterating through arrays
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5


In [3]:
for x in np.nditer(a.T):
    print(x)

0
1
2
3
4
5


In [4]:
for x in np.nditer(a, op_flags =  ['readwrite']):
    print(x)


0
1
2
3
4
5


In [5]:
for x in np.nditer(a, flags =  ['external_loop']):
    print(x)


[0 1 2 3 4 5]
