In [1]:
import matplotlib.pyplot as plt

In [2]:
x = [1,2,3,4,5]
y = [1,2,3,4,5]

In [3]:
plt.scatter(x,y)

In [4]:
plt.plot()

[]

In [5]:
plt.plot([1,2,3,4,5,6])

In [4]:
import numpy as np

In [5]:
nx, ny  = (3,2)

In [6]:
nx

3

In [7]:
ny

2

In [8]:
x = np.linspace(0, 1, nx)
y = np.linspace(0,1,ny)

In [9]:
x

array([0. , 0.5, 1. ])

In [10]:
y

array([0., 1.])

In [11]:
xv, yv = np.meshgrid(x,y)

In [12]:
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [13]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

In [14]:
xv, yv = np.meshgrid(x,y, sparse = True)

In [15]:
xv

array([[0. , 0.5, 1. ]])

In [16]:
yv

array([[0.],
       [1.]])

In [17]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-5, 5, 0.1)

In [18]:
xx, yy = np.meshgrid(x,y, sparse = True)

In [19]:
xx

array([[-5.00000000e+00, -4.90000000e+00, -4.80000000e+00,
        -4.70000000e+00, -4.60000000e+00, -4.50000000e+00,
        -4.40000000e+00, -4.30000000e+00, -4.20000000e+00,
        -4.10000000e+00, -4.00000000e+00, -3.90000000e+00,
        -3.80000000e+00, -3.70000000e+00, -3.60000000e+00,
        -3.50000000e+00, -3.40000000e+00, -3.30000000e+00,
        -3.20000000e+00, -3.10000000e+00, -3.00000000e+00,
        -2.90000000e+00, -2.80000000e+00, -2.70000000e+00,
        -2.60000000e+00, -2.50000000e+00, -2.40000000e+00,
        -2.30000000e+00, -2.20000000e+00, -2.10000000e+00,
        -2.00000000e+00, -1.90000000e+00, -1.80000000e+00,
        -1.70000000e+00, -1.60000000e+00, -1.50000000e+00,
        -1.40000000e+00, -1.30000000e+00, -1.20000000e+00,
        -1.10000000e+00, -1.00000000e+00, -9.00000000e-01,
        -8.00000000e-01, -7.00000000e-01, -6.00000000e-01,
        -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
        -2.00000000e-01, -1.00000000e-01, -1.77635684e-1

In [20]:
yy

array([[-5.00000000e+00],
       [-4.90000000e+00],
       [-4.80000000e+00],
       [-4.70000000e+00],
       [-4.60000000e+00],
       [-4.50000000e+00],
       [-4.40000000e+00],
       [-4.30000000e+00],
       [-4.20000000e+00],
       [-4.10000000e+00],
       [-4.00000000e+00],
       [-3.90000000e+00],
       [-3.80000000e+00],
       [-3.70000000e+00],
       [-3.60000000e+00],
       [-3.50000000e+00],
       [-3.40000000e+00],
       [-3.30000000e+00],
       [-3.20000000e+00],
       [-3.10000000e+00],
       [-3.00000000e+00],
       [-2.90000000e+00],
       [-2.80000000e+00],
       [-2.70000000e+00],
       [-2.60000000e+00],
       [-2.50000000e+00],
       [-2.40000000e+00],
       [-2.30000000e+00],
       [-2.20000000e+00],
       [-2.10000000e+00],
       [-2.00000000e+00],
       [-1.90000000e+00],
       [-1.80000000e+00],
       [-1.70000000e+00],
       [-1.60000000e+00],
       [-1.50000000e+00],
       [-1.40000000e+00],
       [-1.30000000e+00],
       [-1.2

In [21]:
xx, yy = np.meshgrid(x,y)

In [22]:
xx

array([[-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       ...,
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9],
       [-5. , -4.9, -4.8, ...,  4.7,  4.8,  4.9]])

In [23]:
yy

array([[-5. , -5. , -5. , ..., -5. , -5. , -5. ],
       [-4.9, -4.9, -4.9, ..., -4.9, -4.9, -4.9],
       [-4.8, -4.8, -4.8, ..., -4.8, -4.8, -4.8],
       ...,
       [ 4.7,  4.7,  4.7, ...,  4.7,  4.7,  4.7],
       [ 4.8,  4.8,  4.8, ...,  4.8,  4.8,  4.8],
       [ 4.9,  4.9,  4.9, ...,  4.9,  4.9,  4.9]])

In [24]:
np.mgrid[0:5, 0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [25]:
xx, yy = np.mgrid[0:5, 0:5]

In [26]:
xx

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [27]:
yy

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [46]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [45]:
x = randn(10000)

In [47]:
hist(x,100)

(array([  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   1.,   0.,   2.,   1.,   0.,   2.,   0.,   2.,   6.,   3.,
          8.,   5.,  16.,  10.,  11.,  20.,  21.,  24.,  38.,  31.,  43.,
         55.,  55.,  71.,  79.,  82.,  85., 127., 147., 148., 138., 198.,
        193., 193., 237., 250., 226., 264., 297., 286., 302., 297., 289.,
        341., 339., 334., 269., 319., 323., 318., 315., 304., 258., 249.,
        239., 222., 222., 177., 202., 170., 146., 152., 116., 102.,  89.,
         85.,  49.,  67.,  54.,  55.,  46.,  35.,  24.,  22.,  13.,  18.,
         16.,  10.,  13.,   6.,   3.,   5.,   1.,   1.,   3.,   1.,   0.,
          3.]),
 array([-4.73483911, -4.65211048, -4.56938186, -4.48665323, -4.40392461,
        -4.32119598, -4.23846736, -4.15573873, -4.07301011, -3.99028148,
        -3.90755286, -3.82482423, -3.74209561, -3.65936698, -3.57663835,
        -3.49390973, -3.4111811 , -3.32845248, -3.24572385, -3.16299523,
        -3.0802666 , -2.99

In [33]:
fig = figure()

In [34]:
ax = fig.add_subplot(2,2,1)
y = np.random.rand(100)
plt.plot(y)
ax.set_title('i')

#panel 2
ax =  fig.add_subplot(2,2,2)
y = np.random.rand(5)
x = np.arange(5)
plt.bar(x,y)
ax.set_title('2')

#panel 3
ax = fig.add_subplot(2,2,3)
y = np.random.rand(5)
y = y/sum(y)
y[y<.05] = .05
plt.pie(y)
ax.set_title('3')

#panel 4
ax = fig.add_subplot(2,2,4)
z = np.random.randn(100,2)
z[:,1] = 0.5 * z[:,0] + np.sqrt(0.5) * z[:,1]
x = z[:,0]
y = z[:,1]
plt.scatter(x,y)
ax.set_title('4')
plt.draw()

In [40]:
plt.clf()

In [38]:
x = np.cumsum(np.random.randn(100,3), axis =0)
plt.plot(x[:,0], 'b-', label = 'series1')
plt.hold(True)
plt.plot(x[:,1], 'g-', label = 'series2')
plt.plot(x[:,2], 'r:', label = 'series3')
plt.legend()
plt.title('Basic legend')

In [41]:
plt.plot(x[:,0], 'b-', label = 'series1')
plt.hold(True)
plt.plot(x[:,1], 'g-', label = 'series2')
plt.plot(x[:,2], 'r:', label = 'series3')
plt.legend(loc=0,frameon=False, title='The Legend')
plt.title('Basic legend')

In [42]:
plt.figure()

In [43]:
y = np.random.normal(loc=0.5, scale=0.4, size=1000)
y = y[(y > 0) & (y < 1)]
y.sort()
x = np.arange(len(y))
# plot with various axes scales
plt.figure(1)
# linear
plt.subplot(221)
plt.plot(x, y)
plt.yscale('linear')
plt.title('linear')
plt.grid(True)
# log
plt.subplot(222)
plt.plot(x, y)
plt.yscale('log')
plt.title('log')
plt.grid(True)
# symmetric log
plt.subplot(223)
plt.plot(x, y - y.mean())
plt.yscale('symlog', linthreshy=0.05)
plt.title('symlog')
plt.grid(True)
# logit
plt.subplot(224)
plt.plot(x, y)
plt.yscale('logit')
plt.title('logit')
plt.grid(True)

In [44]:
plot()

[]