In [1]:
#labelencoder
from sklearn import preprocessing
import numpy as np

In [2]:
le = preprocessing.LabelEncoder()
le.fit([1,2,2,6])

LabelEncoder()

In [3]:
le.classes_

array([1, 2, 6])

In [4]:
le.transform([1,2,2,6])

array([0, 1, 1, 2], dtype=int64)

In [5]:
le.inverse_transform([0,1,1,2])

C:\Users\jeffnerd\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([1, 2, 2, 6])

In [6]:
le.fit(["paris", "paris","tokyo","amsterdam"])

LabelEncoder()

In [7]:
list(le.classes_)

['amsterdam', 'paris', 'tokyo']

In [8]:
le.transform(["amsterdam","paris","tokyo"])

array([0, 1, 2], dtype=int64)

In [9]:
list(le.inverse_transform([0,1,2]))


C:\Users\jeffnerd\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


['amsterdam', 'paris', 'tokyo']

In [10]:
list(le.inverse_transform([1,1,2]))


C:\Users\jeffnerd\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


['paris', 'paris', 'tokyo']

In [12]:
le.fit_transform(['paris','paris','tokyo'])

array([0, 0, 1], dtype=int64)

In [15]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

In [16]:
enc.fit([[0,0,3],[1,1,0],[1,0,2]])

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [17]:
enc.n_values_

array([2, 2, 4])

In [18]:
enc.feature_indices_

array([0, 2, 4, 8], dtype=int32)

In [21]:
enc.transform([[0,1,3]]).toarray()

array([[1., 0., 0., 1., 0., 0., 1.]])

In [25]:
#polynomial expansion
x = np.arange(6).reshape(3,2)

In [23]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [26]:
poly = PolynomialFeatures(2)

In [27]:
poly.fit_transform(x)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [28]:
#label binarizer
from sklearn.preprocessing import LabelBinarizer

In [29]:
lb = LabelBinarizer()

In [30]:
lb.fit([1,2,6,4,2])

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [31]:
lb.classes_

array([1, 2, 4, 6])

In [32]:
lb.transform([1,6])

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [33]:
lb.fit_transform(["yes","no","yes","no"])

array([[1],
       [0],
       [1],
       [0]])

In [34]:
#multiclass ve multilabel fitting
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer

In [35]:
x = [[1,2],[2,4],[4,5], [3,2],[3,1]]
y = [0,0,1,1,2]

In [37]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(x,y).predict(x)

array([0, 0, 1, 1, 2])

In [38]:
y = LabelBinarizer().fit_transform(y)

In [39]:
classif.fit(x,y).predict(x)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
#for multilabel binarizer
y = [[0,1],[1,3],[0,2], [2,4],[3,4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(x,y).predict(x)

array([[1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]])

In [43]:
from sklearn.preprocessing import Imputer

In [44]:
imp = Imputer(missing_values="NaN",strategy="mean",axis=0)
imp.fit([[1,2],[np.nan,3],[7,6]])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [45]:
x = [[np.nan,2],[6,np.nan],[7,6]]

In [46]:
print(imp.transform(x))

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]
